### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by Axel3026** [macrosalt/Microsoft-Rewards-bot#4]
E:\Descargas\Microsoft-Rewards-bot-salt-local>py ms_rewards_farmer.py --session --error --fast
C:\Users\Axel\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "E:\Descargas\Microsoft-Rewards-bot-salt-local\ms_rewards_farmer.py", line 1275, in <module>
    main()
  File "E:\Descargas\Microsoft-Rewards-bot-salt-local\ms_rewards_farmer.py", line 1235, in main
    display = Display(visible=0, size=(900, 800))
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python310\lib\site-packages\pyvirtualdisplay\display.py", line 54, in __init__
    self._obj = cls(
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python310\lib\site-packages\pyvirtualdisplay\xvfb.py", line 44, in __init__
    AbstractDisplay.__init__(
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python310\lib\site-packages\pyvirtualdisplay\abstractdisplay.py", line 85, in __init__
    helptext = get_helptext(program)
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python310\lib\site-packages\pyvirtualdisplay\util.py", line 13, in get_helptext
    p = subprocess.Popen(
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Axel\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

**Comment by Axel3026** [comment]
I don't know anything about programming, I would like there to be a tutorial or the version that I have to use
